# Static code analysis for markdown files

name: MDLint

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "check"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Node.js 18.17
        uses: actions/setup-node@v3
        with:
          node-version: "18.17"
      - name: Install dependencies
        run: |
            npm install --save-dev textlint
            npm install --save-dev textlint-rule-no-todo
            npx textlint --init
      - name: Run code analysis
        run: npx textlint $(git ls-files '*.md')
